//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_BlogMaster_CategoryMaster", "CategoryMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.CategoryMaster), "BlogMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.BlogMaster), true)]
[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_BlogMaster_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.User), "BlogMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.BlogMaster), true)]
[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_BlogThread_BlogMaster", "BlogMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.BlogMaster), "BlogThread", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.BlogThread), true)]
[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_BlogThread_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.User), "BlogThread", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.BlogThread), true)]
[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.CategoryMaster), "ReferenceSitesMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.ReferenceSitesMaster), true)]
[assembly: EdmRelationshipAttribute("StopShopDBModel", "FK_SubCategoryMaster_CategoryMaster", "CategoryMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OneStopShop.Models.CategoryMaster), "SubCategoryMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OneStopShop.Models.SubCategoryMaster), true)]

#endregion

namespace OneStopShop.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StopShopDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StopShopDBEntities object using the connection string found in the 'StopShopDBEntities' section of the application configuration file.
        /// </summary>
        public StopShopDBEntities() : base("name=StopShopDBEntities", "StopShopDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StopShopDBEntities object.
        /// </summary>
        public StopShopDBEntities(string connectionString) : base(connectionString, "StopShopDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StopShopDBEntities object.
        /// </summary>
        public StopShopDBEntities(EntityConnection connection) : base(connection, "StopShopDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogMaster> BlogMasters
        {
            get
            {
                if ((_BlogMasters == null))
                {
                    _BlogMasters = base.CreateObjectSet<BlogMaster>("BlogMasters");
                }
                return _BlogMasters;
            }
        }
        private ObjectSet<BlogMaster> _BlogMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogThread> BlogThreads
        {
            get
            {
                if ((_BlogThreads == null))
                {
                    _BlogThreads = base.CreateObjectSet<BlogThread>("BlogThreads");
                }
                return _BlogThreads;
            }
        }
        private ObjectSet<BlogThread> _BlogThreads;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoryMaster> CategoryMasters
        {
            get
            {
                if ((_CategoryMasters == null))
                {
                    _CategoryMasters = base.CreateObjectSet<CategoryMaster>("CategoryMasters");
                }
                return _CategoryMasters;
            }
        }
        private ObjectSet<CategoryMaster> _CategoryMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReferenceSitesMaster> ReferenceSitesMasters
        {
            get
            {
                if ((_ReferenceSitesMasters == null))
                {
                    _ReferenceSitesMasters = base.CreateObjectSet<ReferenceSitesMaster>("ReferenceSitesMasters");
                }
                return _ReferenceSitesMasters;
            }
        }
        private ObjectSet<ReferenceSitesMaster> _ReferenceSitesMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubCategoryMaster> SubCategoryMasters
        {
            get
            {
                if ((_SubCategoryMasters == null))
                {
                    _SubCategoryMasters = base.CreateObjectSet<SubCategoryMaster>("SubCategoryMasters");
                }
                return _SubCategoryMasters;
            }
        }
        private ObjectSet<SubCategoryMaster> _SubCategoryMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogMasters(BlogMaster blogMaster)
        {
            base.AddObject("BlogMasters", blogMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogThreads EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogThreads(BlogThread blogThread)
        {
            base.AddObject("BlogThreads", blogThread);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoryMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoryMasters(CategoryMaster categoryMaster)
        {
            base.AddObject("CategoryMasters", categoryMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReferenceSitesMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReferenceSitesMasters(ReferenceSitesMaster referenceSitesMaster)
        {
            base.AddObject("ReferenceSitesMasters", referenceSitesMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubCategoryMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubCategoryMasters(SubCategoryMaster subCategoryMaster)
        {
            base.AddObject("SubCategoryMasters", subCategoryMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="BlogMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogMaster object.
        /// </summary>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static BlogMaster CreateBlogMaster(global::System.Int32 blogId, global::System.Int32 categoryId, global::System.Int32 userId, global::System.String description, global::System.DateTime dateTime, global::System.String userName)
        {
            BlogMaster blogMaster = new BlogMaster();
            blogMaster.BlogId = blogId;
            blogMaster.CategoryId = categoryId;
            blogMaster.UserId = userId;
            blogMaster.Description = description;
            blogMaster.DateTime = dateTime;
            blogMaster.UserName = userName;
            return blogMaster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                if (_BlogId != value)
                {
                    OnBlogIdChanging(value);
                    ReportPropertyChanging("BlogId");
                    _BlogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogId");
                    OnBlogIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogId;
        partial void OnBlogIdChanging(global::System.Int32 value);
        partial void OnBlogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogMaster_CategoryMaster", "CategoryMaster")]
        public CategoryMaster CategoryMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "CategoryMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "CategoryMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CategoryMaster> CategoryMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "CategoryMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CategoryMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "CategoryMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogMaster_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogMaster_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogMaster_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogMaster_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("StopShopDBModel.FK_BlogMaster_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogThread_BlogMaster", "BlogThread")]
        public EntityCollection<BlogThread> BlogThreads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogThread>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogThread");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogThread>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogThread", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="BlogThread")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogThread : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogThread object.
        /// </summary>
        /// <param name="blogThreadId">Initial value of the BlogThreadId property.</param>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static BlogThread CreateBlogThread(global::System.Int32 blogThreadId, global::System.Int32 blogId, global::System.Int32 userId, global::System.String description, global::System.DateTime dateTime, global::System.String userName)
        {
            BlogThread blogThread = new BlogThread();
            blogThread.BlogThreadId = blogThreadId;
            blogThread.BlogId = blogId;
            blogThread.UserId = userId;
            blogThread.Description = description;
            blogThread.DateTime = dateTime;
            blogThread.UserName = userName;
            return blogThread;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogThreadId
        {
            get
            {
                return _BlogThreadId;
            }
            set
            {
                if (_BlogThreadId != value)
                {
                    OnBlogThreadIdChanging(value);
                    ReportPropertyChanging("BlogThreadId");
                    _BlogThreadId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogThreadId");
                    OnBlogThreadIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogThreadId;
        partial void OnBlogThreadIdChanging(global::System.Int32 value);
        partial void OnBlogThreadIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                OnBlogIdChanging(value);
                ReportPropertyChanging("BlogId");
                _BlogId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlogId");
                OnBlogIdChanged();
            }
        }
        private global::System.Int32 _BlogId;
        partial void OnBlogIdChanging(global::System.Int32 value);
        partial void OnBlogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogThread_BlogMaster", "BlogMaster")]
        public BlogMaster BlogMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogMaster>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogMaster>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BlogMaster> BlogMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogMaster>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BlogMaster>("StopShopDBModel.FK_BlogThread_BlogMaster", "BlogMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogThread_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogThread_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogThread_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StopShopDBModel.FK_BlogThread_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("StopShopDBModel.FK_BlogThread_User", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="CategoryMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoryMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoryMaster object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static CategoryMaster CreateCategoryMaster(global::System.Int32 categoryId, global::System.String name, global::System.String description)
        {
            CategoryMaster categoryMaster = new CategoryMaster();
            categoryMaster.CategoryId = categoryId;
            categoryMaster.Name = name;
            categoryMaster.Description = description;
            return categoryMaster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhotoURL
        {
            get
            {
                return _PhotoURL;
            }
            set
            {
                OnPhotoURLChanging(value);
                ReportPropertyChanging("PhotoURL");
                _PhotoURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhotoURL");
                OnPhotoURLChanged();
            }
        }
        private global::System.String _PhotoURL;
        partial void OnPhotoURLChanging(global::System.String value);
        partial void OnPhotoURLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogMaster_CategoryMaster", "BlogMaster")]
        public EntityCollection<BlogMaster> BlogMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "BlogMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogMaster>("StopShopDBModel.FK_BlogMaster_CategoryMaster", "BlogMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_ReferenceSitesMaster_CategoryMaster", "ReferenceSitesMaster")]
        public EntityCollection<ReferenceSitesMaster> ReferenceSitesMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReferenceSitesMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "ReferenceSitesMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReferenceSitesMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "ReferenceSitesMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_SubCategoryMaster_CategoryMaster", "SubCategoryMaster")]
        public EntityCollection<SubCategoryMaster> SubCategoryMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubCategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "SubCategoryMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubCategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "SubCategoryMaster", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="ReferenceSitesMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReferenceSitesMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReferenceSitesMaster object.
        /// </summary>
        /// <param name="referenceSitesId">Initial value of the ReferenceSitesId property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="uRL">Initial value of the URL property.</param>
        public static ReferenceSitesMaster CreateReferenceSitesMaster(global::System.Int32 referenceSitesId, global::System.Int32 categoryId, global::System.String name, global::System.String uRL)
        {
            ReferenceSitesMaster referenceSitesMaster = new ReferenceSitesMaster();
            referenceSitesMaster.ReferenceSitesId = referenceSitesId;
            referenceSitesMaster.CategoryId = categoryId;
            referenceSitesMaster.Name = name;
            referenceSitesMaster.URL = uRL;
            return referenceSitesMaster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReferenceSitesId
        {
            get
            {
                return _ReferenceSitesId;
            }
            set
            {
                if (_ReferenceSitesId != value)
                {
                    OnReferenceSitesIdChanging(value);
                    ReportPropertyChanging("ReferenceSitesId");
                    _ReferenceSitesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReferenceSitesId");
                    OnReferenceSitesIdChanged();
                }
            }
        }
        private global::System.Int32 _ReferenceSitesId;
        partial void OnReferenceSitesIdChanging(global::System.Int32 value);
        partial void OnReferenceSitesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster")]
        public CategoryMaster CategoryMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CategoryMaster> CategoryMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CategoryMaster>("StopShopDBModel.FK_ReferenceSitesMaster_CategoryMaster", "CategoryMaster", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="SubCategoryMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubCategoryMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubCategoryMaster object.
        /// </summary>
        /// <param name="subCategoryId">Initial value of the SubCategoryId property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static SubCategoryMaster CreateSubCategoryMaster(global::System.Int32 subCategoryId, global::System.Int32 categoryId, global::System.String name, global::System.String description)
        {
            SubCategoryMaster subCategoryMaster = new SubCategoryMaster();
            subCategoryMaster.SubCategoryId = subCategoryId;
            subCategoryMaster.CategoryId = categoryId;
            subCategoryMaster.Name = name;
            subCategoryMaster.Description = description;
            return subCategoryMaster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubCategoryId
        {
            get
            {
                return _SubCategoryId;
            }
            set
            {
                if (_SubCategoryId != value)
                {
                    OnSubCategoryIdChanging(value);
                    ReportPropertyChanging("SubCategoryId");
                    _SubCategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubCategoryId");
                    OnSubCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _SubCategoryId;
        partial void OnSubCategoryIdChanging(global::System.Int32 value);
        partial void OnSubCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhotoURL
        {
            get
            {
                return _PhotoURL;
            }
            set
            {
                OnPhotoURLChanging(value);
                ReportPropertyChanging("PhotoURL");
                _PhotoURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhotoURL");
                OnPhotoURLChanged();
            }
        }
        private global::System.String _PhotoURL;
        partial void OnPhotoURLChanging(global::System.String value);
        partial void OnPhotoURLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_SubCategoryMaster_CategoryMaster", "CategoryMaster")]
        public CategoryMaster CategoryMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "CategoryMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "CategoryMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CategoryMaster> CategoryMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "CategoryMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CategoryMaster>("StopShopDBModel.FK_SubCategoryMaster_CategoryMaster", "CategoryMaster", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StopShopDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="emailId">Initial value of the EmailId property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String userName, global::System.String password, global::System.String emailId)
        {
            User user = new User();
            user.UserId = userId;
            user.UserName = userName;
            user.Password = password;
            user.EmailId = emailId;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogMaster_User", "BlogMaster")]
        public EntityCollection<BlogMaster> BlogMasters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogMaster>("StopShopDBModel.FK_BlogMaster_User", "BlogMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogMaster>("StopShopDBModel.FK_BlogMaster_User", "BlogMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StopShopDBModel", "FK_BlogThread_User", "BlogThread")]
        public EntityCollection<BlogThread> BlogThreads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogThread>("StopShopDBModel.FK_BlogThread_User", "BlogThread");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogThread>("StopShopDBModel.FK_BlogThread_User", "BlogThread", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
